Add/update queries for pulling Key Usage Indicators data
galaxyproject/gxadmin pull request #149
Opened 2024-03-25 20:45 UTC by afgane

Requested by @bgruening to start including EU data on the [Key Usage Indicators dashboard](https://gxy.io/kui), ported necessary queries to gxadmin.

2024-03-26 03:43 UTC, nuwang commented on parts/22-query.sh
> +											tool_id                                 | count
Looks like the formatter has caused a misalignment of columns

2024-03-26 08:25 UTC, hexylena requested changes
I'll review again once the whitespace issue is fixed since it's making the diff harder to read in places.

Looking forward to this change! 

I guess you should also consider coordinating with  usegalaxy.fr (which meets the usegalaxy.* criteria) to see if they wants to submit aggregated user statistics to this central dashboard.

2024-03-26 08:25 UTC, hexylena commented on parts/22-query.sh
> +											tool_id                                 | count
Yes. The 4 spacing is _intentional_ here, it generates a code block without being fenced which is more difficult to parse in bash. Could you please revert these spacing changes?

2024-03-26 08:25 UTC, hexylena commented on parts/22-query.sh
> -		  2020-08-01 | Group_1    |     1
perhaps leave both examples?  They function differently, it's nice to have examples of alternative invocations for users.

2024-03-26 08:25 UTC, hexylena commented on parts/22-query.sh
> +		elif [[ -n "$where_y" ]]; then
fi/elif is incorrect

2024-03-26 08:25 UTC, hexylena commented on parts/22-query.sh
> +	fi
```suggestion
	if [[ -z "$arg_month" ]]; then
		arg_month=$(date +%Y-%m)
	fi
```

2024-03-26 08:25 UTC, hexylena commented on parts/22-query.sh
> +	if [ $# -eq 0 ]; then
```suggestion
	if [[ -z "$arg_month" ]]; then
```

there is always the chance I mess with which args are passed to functions, so checking the precise variable will be safer.

2024-03-26 18:57 UTC, afgane commented
I reverted the big tabs change; sorry about that. It should be easier to review now. 

Thanks for the initial comments.

And yes, .fr as well as any other .* instance will be more than welcome to contribute the data. Starting with the big three as exemplars, plus getting the queries into here, will hopefully make that more palatable for other servers.

2024-03-27 13:46 UTC, hexylena reviewed
This looks great, thank you for the KPI queries, I think this is a great batch of changes, I have a small comment on standardisation of the CLI across the commands but I think this is very close to done.

Thanks for filling out the changelog as well :)

2024-03-27 13:46 UTC, hexylena commented on parts/22-query.sh
> +query_monthly-users-registered(){ ## [year] [YYYY-MM] [--by_group]: Number of users registered
so this one is a bit odd for me, with year + yyyy-mm support. These arguments effectively act as filter, and I think we can simplify them, and make them match up a bit better with other commands like `query_monthly-job-runtimes`

```suggestion
query_monthly-users-registered(){ ## [--year=<YYYY>] [--month=<MM>] [--by_group]: Number of users registered
```

I think this could then be copied and pasted across the rest and we can remove the (lovely!!) use of regexes for matching strings and have a nicer more consistent UX.

2024-03-27 13:46 UTC, hexylena commented on parts/22-query.sh
>  	fi
This could then be simplified massively to something like

```bash
where="WHERE true "
if [[ -n "$arg_year" ]] ; then
  where="AND date_trunc('year', galaxy_user.create_time AT TIME ZONE 'UTC') = '$args-01-01'::date"
fi;
if [[ -n "$arg_month" ]]; then
  where="AND date_trunc('month', galaxy_user.create_time AT TIME ZONE 'UTC')::DATE = '$args-01'::date"
fi;
if [[ -n "$arg_by_group" ]]; then
...
fi
```

which would be a lot cleaner and easier to follow, and maybe behaves in a nicer way for the end user. I'm not sure why they'd want to filter for registrations just in january but it'd also then be an option.

2024-03-27 13:46 UTC, hexylena commented on parts/22-query.sh
> +query_monthly-users-active(){ ## [year] [YYYY-MM] [--by_group]: Number of active users per month, running jobs
same here

2024-03-27 21:00 UTC, afgane commented
Thanks for that suggestion. I also didn't like how that looked but didn't want to change method signatures. This is now much better in terms of the UX as well as cleaner code.

2024-03-28 08:30 UTC, hexylena approved these changes
Yes, fantastic, I love it!

2024-03-28 08:31 UTC, merged

2024-03-28 14:18 UTC, hexylena commented
https://github.com/galaxyproject/gxadmin/releases/tag/v22 is now out.